name: 'Setup'
description: "Setups node.js and yarn to run GitHub Action's jobs."
runs:
  using: 'composite'
  steps:
    - name: 'Setup node.js'
      uses: 'actions/setup-node@v3'
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: 'Install dependencies'
      uses: 'borales/actions-yarn@v4'
      with:
        cmd: install
